version: 1
config:
  - type: physical
    name: eth0
    subnets:
      - type: static
        ipv4: true
        address: 10.209.53.4
        netmask: 255.255.255.0
        gateway: 10.209.53.1
        control: auto
  - type: nameserver
    address: 10.209.53.2
